const AUTH = {
  SIGNUP: 'AUTH_SIGNUP',
  LOGIN: 'AUTH_LOGIN',
  AUTOLOGIN: 'AUTH_AUTOLOGIN',
  SET_USER: 'AUTH_SET_USER',
  FAIL: 'AUTH_FAIL',
};

const USERS = {
  GET_USERS: 'USERS_GET_USERS',
  GET_SELECTED_USER: 'USERS_GET_USER',
  ADD_POST: 'USERS_ADD_POST',
  UPDATE_POST: 'USERS_UPDATE_POST',
  DELETE_POST: 'USERS_DELETE_POST',
  SET_USERS: 'USERS_SET_USERS',
  SET_SELECTED_USER: 'USERS_SET_SELECTED_USER',
  SET_LOADING: 'USERS_SET_LOADING',
  GIVE_BEER: 'USERS_GIVE_BEER',
  FAIL: 'USERS_FAIL',
};

export { AUTH, USERS };
